# Generated by Django 3.1.7 on 2021-04-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tasks',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tasks',
            name='project',
            field=models.CharField(default='', max_length=50),
        ),
    ]
