# Generated by Django 3.1.7 on 2021-04-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210407_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
