# Generated by Django 3.1.7 on 2021-04-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_tasks_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='desc',
            field=models.CharField(default='okok', max_length=500),
        ),
    ]
