# Generated by Django 3.1.7 on 2021-04-08 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20210408_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='due',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tasks',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
    ]
