# Generated by Django 3.1.7 on 2021-04-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20210411_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='due',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='label',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='project',
        ),
    ]
