# Generated by Django 3.1.7 on 2021-04-11 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_tasks_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='due',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
