# Generated by Django 3.1.7 on 2021-04-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_auto_20210411_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='due',
        ),
    ]
