# Generated by Django 3.1.7 on 2021-04-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_remove_tasks_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
    ]
