# Generated by Django 3.1.7 on 2021-04-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_tasks_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default='2021-04-11'),
        ),
    ]
