# Generated by Django 3.1.7 on 2021-04-11 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_auto_20210411_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='due_date',
        ),
        migrations.AddField(
            model_name='tasks',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='created_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='priority2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
