# Generated by Django 3.1.7 on 2021-04-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_auto_20210411_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='priority2',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='project',
        ),
    ]
